---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tbbzcmdz/public_html/2026
    - /bin/cp -R index.html informasjon.html paamelding.html overnatting.html kontakt.html $DEPLOYPATH/
    - /bin/cp -R css images files $DEPLOYPATH/